import { Villa, AddOn, Amenity } from './types';

export const amenities: Amenity[] = [
    { id: 'wifi', name: 'WiFi Gratis', icon: 'Wifi', category: 'general' },
    { id: 'ac', name: 'AC', icon: 'Wind', category: 'general' },
    { id: 'parking', name: 'Parkir Gratis', icon: 'Car', category: 'general' },
    { id: 'kitchen', name: 'Dapur Lengkap', icon: 'ChefHat', category: 'kitchen' },
    { id: 'bbq', name: 'Area BBQ', icon: 'Flame', category: 'outdoor' },
    { id: 'pool', name: 'Kolam Renang', icon: 'Waves', category: 'outdoor' },
    { id: 'garden', name: 'Taman', icon: 'TreeDeciduous', category: 'outdoor' },
    { id: 'tv', name: 'Smart TV', icon: 'Tv', category: 'entertainment' },
    { id: 'netflix', name: 'Netflix', icon: 'Film', category: 'entertainment' },
    { id: 'ps5', name: 'PlayStation 5', icon: 'Gamepad2', category: 'entertainment' },
    { id: 'karaoke', name: 'Karaoke', icon: 'Mic2', category: 'entertainment' },
    { id: 'billiard', name: 'Billiard', icon: 'CircleDot', category: 'entertainment' },
    { id: 'bathtub', name: 'Bathtub', icon: 'Bath', category: 'bathroom' },
    { id: 'waterheater', name: 'Water Heater', icon: 'Thermometer', category: 'bathroom' },
    { id: 'mountain-view', name: 'View Gunung', icon: 'Mountain', category: 'outdoor' },
];

export const addOns: AddOn[] = [
    { id: 'extra-bed', name: 'Extra Bed', description: 'Kasur tambahan untuk 1 orang', price: 150000, icon: 'Bed' },
    { id: 'bbq-package', name: 'Paket BBQ', description: 'Alat BBQ + arang + bumbu marinasi', price: 250000, icon: 'Flame' },
    { id: 'pet-fee', name: 'Biaya Hewan', description: 'Biaya kebersihan untuk hewan peliharaan', price: 100000, icon: 'PawPrint' },
    { id: 'karaoke-system', name: 'Sewa Karaoke', description: 'Set karaoke portable + mic wireless', price: 200000, icon: 'Mic2' },
    { id: 'pool-heating', name: 'Pemanas Kolam', description: 'Pemanas air kolam (per malam)', price: 300000, icon: 'Thermometer' },
    { id: 'jeep-tour', name: 'Jeep Tour', description: 'Tur jeep keliling Batu (4 jam)', price: 500000, icon: 'Truck' },
    { id: 'breakfast', name: 'Sarapan', description: 'Sarapan untuk 2 orang', price: 100000, icon: 'Coffee' },
    { id: 'photography', name: 'Fotografer', description: 'Sesi foto 1 jam + 30 edit foto', price: 350000, icon: 'Camera' },
];

export const villas: Villa[] = [
    {
        id: '1',
        name: 'Villa Puncak Bintang',
        slug: 'villa-puncak-bintang',
        description: 'Villa mewah dengan pemandangan gunung yang memukau. Dilengkapi dengan kolam renang infinity pool, taman luas, dan fasilitas lengkap untuk liburan keluarga yang tak terlupakan. Lokasi strategis dekat dengan tempat wisata populer di Batu.',
        shortDescription: 'Villa premium dengan infinity pool dan view gunung spektakuler',
        images: [
            'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
        ],
        price: 2500000,
        originalPrice: 3500000, // Strikethrough price
        weekendPrice: 3000000,
        highSeasonPrice: 3500000,
        ownerPrice: 1800000,
        ownerWeekendPrice: 2200000,
        ownerHighSeasonPrice: 2600000,
        capacity: 12,
        bedrooms: 4,
        bathrooms: 3,
        poolSize: '8x4 meter',
        hasPool: true,
        petAllowed: true,
        viewType: 'mountain',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'bbq', 'pool', 'garden', 'tv', 'netflix', 'bathtub', 'waterheater', 'mountain-view'].includes(a.id)),
        location: {
            address: 'Jl. Panderman Indah No. 123',
            area: 'Panderman',
        },
        rating: 4.9,
        reviewCount: 128,
        isRecommended: true,
        isTrending: true,
        isBudget: false,
        isLuxury: true,
        bookedDates: ['2026-01-10', '2026-01-11', '2026-01-12', '2026-01-20', '2026-01-21'],
        createdAt: '2024-01-01',
        updatedAt: '2024-12-01',
    },
    {
        id: '2',
        name: 'Villa Apel Hijau',
        slug: 'villa-apel-hijau',
        description: 'Villa nyaman dengan harga terjangkau di tengah kebun apel. Cocok untuk keluarga kecil atau pasangan yang ingin menikmati suasana pedesaan yang asri. Fasilitas lengkap dengan dapur dan area BBQ.',
        shortDescription: 'Villa budget-friendly di tengah kebun apel',
        images: [
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        ],
        price: 850000,
        weekendPrice: 1000000,
        ownerPrice: 600000,
        ownerWeekendPrice: 750000,
        ownerHighSeasonPrice: 750000, // Assuming same as weekend if not specified
        capacity: 6,
        bedrooms: 2,
        bathrooms: 1,
        hasPool: false,
        petAllowed: true,
        viewType: 'garden',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'bbq', 'garden', 'tv'].includes(a.id)),
        location: {
            address: 'Jl. Kebun Apel No. 45',
            area: 'Bumiaji',
        },
        rating: 4.7,
        reviewCount: 89,
        isRecommended: true,
        isTrending: false,
        isBudget: true,
        isLuxury: false,
        bookedDates: ['2026-01-15', '2026-01-16'],
        createdAt: '2024-02-15',
        updatedAt: '2024-11-20',
    },
    {
        id: '3',
        name: 'Villa Langit Biru',
        slug: 'villa-langit-biru',
        description: 'Villa modern dengan desain kontemporer dan pemandangan kota Batu yang gemerlap di malam hari. Dilengkapi dengan jacuzzi outdoor, home theater, dan karaoke room.',
        shortDescription: 'Villa modern dengan city view dan jacuzzi',
        images: [
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
            'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
        ],
        price: 1800000,
        originalPrice: 2500000, // Strikethrough price
        weekendPrice: 2200000,
        ownerPrice: 1300000,
        ownerWeekendPrice: 1600000,
        ownerHighSeasonPrice: 1600000, // Assuming same as weekend if not specified
        capacity: 10,
        bedrooms: 3,
        bathrooms: 2,
        poolSize: '6x3 meter',
        hasPool: true,
        petAllowed: false,
        viewType: 'city',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'pool', 'tv', 'netflix', 'ps5', 'karaoke', 'bathtub', 'waterheater'].includes(a.id)),
        location: {
            address: 'Jl. Selecta View No. 78',
            area: 'Selecta',
        },
        rating: 4.8,
        reviewCount: 156,
        isRecommended: true,
        isTrending: true,
        isBudget: false,
        isLuxury: true,
        bookedDates: ['2026-01-05', '2026-01-06', '2026-01-07'],
        createdAt: '2024-03-10',
        updatedAt: '2024-12-05',
    },
    {
        id: '4',
        name: 'Villa Sawah Indah',
        slug: 'villa-sawah-indah',
        description: 'Rasakan kedamaian di villa dengan pemandangan sawah yang hijau membentang. Design tradisional Jawa dengan sentuhan modern, cocok untuk retreat dan relaksasi.',
        shortDescription: 'Villa tradisional dengan rice field view',
        images: [
            'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
            'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
            'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800',
        ],
        price: 1200000,
        weekendPrice: 1500000,
        ownerPrice: 850000,
        ownerWeekendPrice: 1100000,
        ownerHighSeasonPrice: 1100000, // Assuming same as weekend if not specified
        capacity: 8,
        bedrooms: 3,
        bathrooms: 2,
        hasPool: false,
        petAllowed: true,
        viewType: 'rice-field',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'bbq', 'garden', 'tv', 'waterheater'].includes(a.id)),
        location: {
            address: 'Jl. Persawahan No. 12',
            area: 'Junrejo',
        },
        rating: 4.6,
        reviewCount: 67,
        isRecommended: false,
        isTrending: false,
        isBudget: true,
        isLuxury: false,
        bookedDates: [],
        createdAt: '2024-04-20',
        updatedAt: '2024-10-15',
    },
    {
        id: '5',
        name: 'Villa Grand Arjuna',
        slug: 'villa-grand-arjuna',
        description: 'Villa super mewah dengan kapasitas besar, perfect untuk acara gathering, arisan, atau liburan rombongan. Fasilitas super lengkap termasuk private cinema, ruang meeting, dan kolam renang olympic size.',
        shortDescription: 'Villa mewah kapasitas besar untuk gathering',
        images: [
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
            'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800',
            'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800',
        ],
        price: 5000000,
        weekendPrice: 6500000,
        highSeasonPrice: 8000000,
        ownerPrice: 3500000,
        ownerWeekendPrice: 4500000,
        ownerHighSeasonPrice: 5500000,
        capacity: 25,
        bedrooms: 7,
        bathrooms: 5,
        poolSize: '15x8 meter',
        hasPool: true,
        petAllowed: false,
        viewType: 'mountain',
        amenities: amenities,
        location: {
            address: 'Jl. Arjuna Estate No. 1',
            area: 'Panderman',
        },
        rating: 4.9,
        reviewCount: 45,
        isRecommended: true,
        isTrending: true,
        isBudget: false,
        isLuxury: true,
        bookedDates: ['2026-01-25', '2026-01-26', '2026-01-27', '2026-01-28'],
        createdAt: '2024-05-01',
        updatedAt: '2024-12-10',
    },
    {
        id: '6',
        name: 'Villa Coban Rondo',
        slug: 'villa-coban-rondo',
        description: 'Villa minimalis yang dekat dengan wisata Air Terjun Coban Rondo. Suasana sejuk pegunungan dengan hawa yang segar, ideal untuk escape dari hiruk pikuk kota.',
        shortDescription: 'Villa sejuk dekat Air Terjun Coban Rondo',
        images: [
            'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        ],
        price: 750000,
        weekendPrice: 900000,
        ownerPrice: 500000,
        ownerWeekendPrice: 650000,
        ownerHighSeasonPrice: 650000, // Assuming same as weekend if not specified
        capacity: 4,
        bedrooms: 2,
        bathrooms: 1,
        hasPool: false,
        petAllowed: true,
        viewType: 'mountain',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'tv', 'waterheater'].includes(a.id)),
        location: {
            address: 'Jl. Coban Rondo No. 88',
            area: 'Coban Rondo',
        },
        rating: 4.5,
        reviewCount: 102,
        isRecommended: false,
        isTrending: false,
        isBudget: true,
        isLuxury: false,
        bookedDates: ['2026-01-08', '2026-01-09'],
        createdAt: '2024-06-15',
        updatedAt: '2024-11-30',
    },
    {
        id: '7',
        name: 'Villa Jatim Park',
        slug: 'villa-jatim-park',
        description: 'Villa strategis yang berjalan kaki ke Jatim Park 1, 2, dan Museum Angkut. Perfect untuk keluarga dengan anak-anak yang ingin explore semua wahana wisata Batu.',
        shortDescription: 'Lokasi strategis dekat Jatim Park & Museum Angkut',
        images: [
            'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
            'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        ],
        price: 1500000,
        weekendPrice: 1800000,
        ownerPrice: 1000000,
        ownerWeekendPrice: 1300000,
        ownerHighSeasonPrice: 1300000, // Assuming same as weekend if not specified
        capacity: 8,
        bedrooms: 3,
        bathrooms: 2,
        poolSize: '5x3 meter',
        hasPool: true,
        petAllowed: true,
        viewType: 'city',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'pool', 'tv', 'netflix', 'ps5', 'bathtub'].includes(a.id)),
        location: {
            address: 'Jl. Kartika No. 55',
            area: 'Jatim Park',
        },
        rating: 4.7,
        reviewCount: 234,
        isRecommended: true,
        isTrending: true,
        isBudget: false,
        isLuxury: false,
        bookedDates: ['2026-01-01', '2026-01-02', '2026-01-03'],
        createdAt: '2024-07-01',
        updatedAt: '2024-12-15',
    },
    {
        id: '8',
        name: 'Villa Paralayang',
        slug: 'villa-paralayang',
        description: 'Villa dengan view spektakuler di area Paralayang Batu. Saksikan sunrise dan sunset yang menakjubkan dari balkon villa. Dilengkapi dengan rooftop lounge.',
        shortDescription: 'Villa dengan view Paralayang dan rooftop lounge',
        images: [
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
            'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
            'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800',
        ],
        price: 2000000,
        weekendPrice: 2500000,
        highSeasonPrice: 3000000,
        ownerPrice: 1400000,
        ownerWeekendPrice: 1800000,
        ownerHighSeasonPrice: 2200000,
        capacity: 10,
        bedrooms: 4,
        bathrooms: 3,
        poolSize: '7x4 meter',
        hasPool: true,
        petAllowed: false,
        viewType: 'mountain',
        amenities: amenities.filter(a => ['wifi', 'ac', 'parking', 'kitchen', 'bbq', 'pool', 'garden', 'tv', 'netflix', 'karaoke', 'bathtub', 'waterheater', 'mountain-view'].includes(a.id)),
        location: {
            address: 'Jl. Paralayang View No. 7',
            area: 'Paralayang',
        },
        rating: 4.8,
        reviewCount: 178,
        isRecommended: true,
        isTrending: false,
        isBudget: false,
        isLuxury: true,
        bookedDates: ['2026-01-18', '2026-01-19'],
        createdAt: '2024-08-10',
        updatedAt: '2024-12-20',
    },
];

export const areas = [
    { id: 'panderman', name: 'Panderman', villaCount: 2 },
    { id: 'bumiaji', name: 'Bumiaji', villaCount: 1 },
    { id: 'selecta', name: 'Selecta', villaCount: 1 },
    { id: 'junrejo', name: 'Junrejo', villaCount: 1 },
    { id: 'coban-rondo', name: 'Coban Rondo', villaCount: 1 },
    { id: 'jatim-park', name: 'Jatim Park', villaCount: 1 },
    { id: 'paralayang', name: 'Paralayang', villaCount: 1 },
];

export const testimonials = [
    {
        id: '1',
        name: 'Budi Santoso',
        avatar: 'https://i.pravatar.cc/100?img=1',
        rating: 5,
        comment: 'Villa Puncak Bintang luar biasa! View gunung yang spektakuler dan fasilitas yang super lengkap. Anak-anak sangat happy dengan kolam renangnya.',
        villaName: 'Villa Puncak Bintang',
        date: 'Desember 2024',
    },
    {
        id: '2',
        name: 'Sari Wijaya',
        avatar: 'https://i.pravatar.cc/100?img=5',
        rating: 5,
        comment: 'Booking lewat Villa Batu sangat mudah dan cepat. Response admin juga friendly banget. Pasti bakal repeat order!',
        villaName: 'Villa Langit Biru',
        date: 'November 2024',
    },
    {
        id: '3',
        name: 'Rendra Pratama',
        avatar: 'https://i.pravatar.cc/100?img=3',
        rating: 5,
        comment: 'Gathering kantor di Villa Grand Arjuna sukses besar! Tempatnya luas, fasilitasnya lengkap, dan harganya worth it untuk kapasitas segitu.',
        villaName: 'Villa Grand Arjuna',
        date: 'Oktober 2024',
    },
];

// Extensive villa reviews data
export const villaReviews: { [villaId: string]: Array<{ id: string; name: string; avatar: string; rating: number; comment: string; date: string }> } = {
    '1': [ // Villa Puncak Bintang
        { id: 'r1', name: 'Budi Santoso', avatar: 'https://i.pravatar.cc/100?img=1', rating: 5, comment: 'Villa luar biasa! View gunung spektakuler, kolam renang bersih, dan fasilitas lengkap. Anak-anak sangat happy!', date: '2024-12-15' },
        { id: 'r2', name: 'Dewi Kusuma', avatar: 'https://i.pravatar.cc/100?img=5', rating: 5, comment: 'Perfect untuk liburan keluarga. Dapur lengkap, kamar nyaman, dan pemandangan sunrise-nya amazing!', date: '2024-12-10' },
        { id: 'r3', name: 'Ahmad Fauzi', avatar: 'https://i.pravatar.cc/100?img=8', rating: 4, comment: 'Bagus banget villanya, cuma wifi agak lemot. Tapi overall sangat recommended!', date: '2024-11-28' },
        { id: 'r4', name: 'Rina Marlina', avatar: 'https://i.pravatar.cc/100?img=9', rating: 5, comment: 'Sudah 3x menginap di sini dan selalu puas. Pemilik ramah dan responsif.', date: '2024-11-20' },
        { id: 'r5', name: 'Hendra Wijaya', avatar: 'https://i.pravatar.cc/100?img=12', rating: 5, comment: 'Best villa di Batu! Infinity pool-nya keren banget, view langsung ke Gunung Panderman.', date: '2024-11-15' },
    ],
    '2': [ // Villa Apel Hijau
        { id: 'r6', name: 'Siti Nurhaliza', avatar: 'https://i.pravatar.cc/100?img=10', rating: 5, comment: 'Villa budget friendly tapi kualitas ga murahan! Suasana kebun apelnya bikin tenang.', date: '2024-12-08' },
        { id: 'r7', name: 'Joko Susilo', avatar: 'https://i.pravatar.cc/100?img=11', rating: 4, comment: 'Cocok untuk pasangan atau keluarga kecil. Lokasinya tenang dan asri.', date: '2024-11-25' },
        { id: 'r8', name: 'Maya Sari', avatar: 'https://i.pravatar.cc/100?img=15', rating: 5, comment: 'Harga terjangkau, tempat bersih, pemilik ramah. Recommended!', date: '2024-11-18' },
        { id: 'r9', name: 'Agus Pratomo', avatar: 'https://i.pravatar.cc/100?img=13', rating: 4, comment: 'Area BBQ nya enak, bisa bakar-bakar sambil ngobrol. Suasananya homey banget.', date: '2024-10-30' },
    ],
    '3': [ // Villa Langit Biru
        { id: 'r10', name: 'Putri Amanda', avatar: 'https://i.pravatar.cc/100?img=16', rating: 5, comment: 'Jacuzzi-nya perfect! City view malam hari keren banget. Worth every penny.', date: '2024-12-12' },
        { id: 'r11', name: 'Ricky Martin', avatar: 'https://i.pravatar.cc/100?img=17', rating: 5, comment: 'Karaoke room super seru! PS5-nya juga ada. Kids approved 100%!', date: '2024-12-05' },
        { id: 'r12', name: 'Linda Kusuma', avatar: 'https://i.pravatar.cc/100?img=20', rating: 4, comment: 'Modern dan stylish. Cocok untuk anak muda atau couple getaway.', date: '2024-11-22' },
        { id: 'r13', name: 'Dimas Prasetyo', avatar: 'https://i.pravatar.cc/100?img=18', rating: 5, comment: 'Staycation anniversary di sini berasa honeymoon lagi. Romantis!', date: '2024-11-10' },
        { id: 'r14', name: 'Anita Dewi', avatar: 'https://i.pravatar.cc/100?img=21', rating: 5, comment: 'Fasilitasnya lengkap banget, dari karaoke sampai Netflix. No boring!', date: '2024-10-28' },
    ],
    '4': [ // Villa Sawah Indah
        { id: 'r15', name: 'Bambang Sutrisno', avatar: 'https://i.pravatar.cc/100?img=22', rating: 5, comment: 'View sawah-nya bikin rileks. Cocok untuk healing dari rutinitas kota.', date: '2024-12-01' },
        { id: 'r16', name: 'Kartini Wulan', avatar: 'https://i.pravatar.cc/100?img=25', rating: 4, comment: 'Suasana pedesaan yang autentik. Tidur ditemani suara kodok, so peaceful!', date: '2024-11-15' },
        { id: 'r17', name: 'Irfan Hakim', avatar: 'https://i.pravatar.cc/100?img=23', rating: 5, comment: 'Design tradisional Jawa-nya keren. Berasa pulang kampung nenek!', date: '2024-10-20' },
    ],
    '5': [ // Villa Grand Arjuna
        { id: 'r18', name: 'Corporate Team A', avatar: 'https://i.pravatar.cc/100?img=30', rating: 5, comment: 'Gathering 25 orang muat semua! Ruang meeting, cinema, kolam renang amazing!', date: '2024-12-18' },
        { id: 'r19', name: 'Keluarga Besar Hadi', avatar: 'https://i.pravatar.cc/100?img=31', rating: 5, comment: 'Arisan keluarga besar 7 KK lancar jaya! Kapasitas besar, fasilitas super lengkap.', date: '2024-12-10' },
        { id: 'r20', name: 'Event Organizer', avatar: 'https://i.pravatar.cc/100?img=32', rating: 5, comment: 'Perfect venue untuk retreat perusahaan. Private, luas, dan profesional.', date: '2024-11-28' },
    ],
    '6': [ // Villa Coban Rondo
        { id: 'r21', name: 'Nadia Safitri', avatar: 'https://i.pravatar.cc/100?img=35', rating: 5, comment: 'Dekat air terjun, hawanya sejuk banget! Cocok untuk escape dari panas.', date: '2024-12-05' },
        { id: 'r22', name: 'Eko Prasetyo', avatar: 'https://i.pravatar.cc/100?img=33', rating: 4, comment: 'Villa minimalis tapi nyaman. Lokasi strategis dekat wisata.', date: '2024-11-20' },
        { id: 'r23', name: 'Siska Amelia', avatar: 'https://i.pravatar.cc/100?img=36', rating: 5, comment: 'Budget friendly dan bersih. Recommended untuk backpacker!', date: '2024-10-15' },
    ],
    '7': [ // Villa Jatim Park
        { id: 'r24', name: 'Keluarga Susanto', avatar: 'https://i.pravatar.cc/100?img=40', rating: 5, comment: 'Jalan kaki ke Jatim Park! Anak-anak hepi banget, ortu ga capek nyetir.', date: '2024-12-20' },
        { id: 'r25', name: 'Diana Puspita', avatar: 'https://i.pravatar.cc/100?img=41', rating: 5, comment: 'Lokasi super strategis. Museum Angkut, BNS, Jatim Park semua deket!', date: '2024-12-08' },
        { id: 'r26', name: 'Rio Febrian', avatar: 'https://i.pravatar.cc/100?img=42', rating: 4, comment: 'Kolam renangnya oke, PS5 ada. Anak-anak betah ga mau pulang.', date: '2024-11-25' },
        { id: 'r27', name: 'Mega Putri', avatar: 'https://i.pravatar.cc/100?img=45', rating: 5, comment: 'Best location ever! Hemat waktu dan tenaga untuk explore wisata Batu.', date: '2024-11-10' },
    ],
    '8': [ // Villa Paralayang
        { id: 'r28', name: 'Photographer Pro', avatar: 'https://i.pravatar.cc/100?img=50', rating: 5, comment: 'Sunrise dan sunset dari sini juara! Foto prewedding client sukses besar.', date: '2024-12-15' },
        { id: 'r29', name: 'Yoga Aditya', avatar: 'https://i.pravatar.cc/100?img=51', rating: 5, comment: 'Rooftop lounge-nya keren banget. Nongkrong sambil lihat lampu kota malam.', date: '2024-12-01' },
        { id: 'r30', name: 'Bella Maharani', avatar: 'https://i.pravatar.cc/100?img=48', rating: 4, comment: 'View 180 derajat pegunungan. Karaoke seru, pool bersih. Worth it!', date: '2024-11-18' },
        { id: 'r31', name: 'Denny Cagur', avatar: 'https://i.pravatar.cc/100?img=52', rating: 5, comment: 'Trip paralayang + nginep di sini = liburan sempurna! Highly recommended.', date: '2024-10-25' },
    ],
};

export const WHATSAPP_NUMBER = '6281234567890';

